get_local_chans: fix regex for double digits and catch exception
exception: sometimes regex seems to return the entire string here,
at this time it's not clear to me why, but it was crashing the dialplan
Return a large number if this happens so we don't allow non time
limited calls when the BTS' are busy"
Log a message with the number of chans in use.